apiRules:
# UWP XAML Metadata provider:
- exclude:
    uidRegex: ^Esri\.ArcGISRuntime\.Toolkit\.Esri_ArcGISRuntime_Toolkit_XamlTypeInfo
- exclude:
    uidRegex: ^Esri\.ArcGISRuntime\.Toolkit\.Xamarin\.Forms\.Esri_ArcGISRuntime_Toolkit_Xamarin_Forms_XamlTypeInfo
# Android Resource:
- exclude:
    uidRegex: ^Esri\.ArcGISRuntime\.Toolkit\.Resource
- exclude:
    uidRegex: ^Esri\.ArcGISRuntime\.Toolkit\.Resource\.Xamarin\.Forms\.Resource
- exclude:
    uidRegex: ^Esri\.ArcGISRuntime\.ARToolkit\.Resource
- exclude:
    uidRegex: ^Esri\.ArcGISRuntime\.ARToolkit\.Resource\.Xamarin\.Forms\.Resource
